# Generated by Django 4.2.26 on 2026-03-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва теми')),
                ('school_class', models.CharField(choices=[('7', '7 Клас'), ('8', '8 Клас'), ('9', '9 Клас'), ('10', '10 Клас'), ('11', '11 Клас')], max_length=2, verbose_name='Клас')),
                ('content', models.TextField(verbose_name='Зміст теми')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Посилання на відео')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='PDF файл')),
            ],
        ),
    ]
